### ISSUE TITLE
Add an Except category option

### ISSUE THREAD

**Issue by timh57** [mkrdip/category-posts-widget#1]
Category Posts is a great plugin, but it could be greater if there was an option for "except this category". If the except option is enabled then the widget shows all posts except the chosen category.

I've applied this customisation to the copy of the plugin I use (originally 3.3 and now 4) and it works fine.

My post categories consist of "news" and a bunch of blog categories. With this change I can have a list of recent "news" items and a list of recent "blog" entries - where blog entries are everything except news.

**Comment by DanielFloeter** [comment]
Hi Tim, 

thanks for your pull request. Your code (pull request: # 2 "Update cat-posts.php") was merged with commit 905156c.

If you except a category and no headline is specified, then it disappears. (It doesn't displayed the excluded category as a heading!) But you can define a separate heading.

Best regards
