### ISSUE TITLE
New Beta Version has errors on WP Debug Mode

### ISSUE THREAD

**Issue by mkrdip** [mkrdip/category-posts-widget#13]
Screenshot: 
![image](https://cloud.githubusercontent.com/assets/3819579/8687824/ec75ea0a-2ab5-11e5-880c-149b20c6916c.png)

**Comment by DanielFloeter** [comment]
Uuuups.
I don't use isset each time I use 'disable_css'.
I had made a bugfix jet (efbab8b6410a0f397819679d1f5fe1b468b38e07).
