### ISSUE TITLE
New Styling has no effect on new beta version

### ISSUE THREAD

**Issue by mkrdip** [mkrdip/category-posts-widget#14]
Previous Version: 
![image](https://cloud.githubusercontent.com/assets/3819579/8687987/e5bcacf6-2ab7-11e5-89cb-aac6d6882585.png)

Check, Thumbnail Left - Excerpt Right

Newest Version: 
![image](https://cloud.githubusercontent.com/assets/3819579/8687951/96906fd2-2ab7-11e5-8de6-d3546fb46ba3.png)

**Comment by DanielFloeter** [comment]
Hi Mrinal,
Please check the bug fix now again. Thank you.

I think it was a consequence of errors?

I give much respect does not delete existing CSS classes for the Widget update, like in line 52 (class="cat-post-widget"). Certainly users use this in their own style-files? 
The HTML-output shouldn't change. HTML does not change. If, then, I have new classes used with "cat-post" prefix.
