### ISSUE TITLE
On Click Post or Category Title leads to 404 not found page

### ISSUE THREAD

**Issue by ishantsaxena** [mkrdip/category-posts-widget#15]
Hi ,
I am using this plugin and this is a great plugin.But the Problem is when i click the Category title or the Post title it leads to the 404 not found page.

I tried this with custom permalink but it doen't work.I tried this with default permalink then it work.But i want seo friendly permalink

**Comment by DanielFloeter** [comment]
Hello Ishantsaxena,

try out the link to the category page on the menu as a menu tab. It might because of the fact that your server used the mod_rewrite misconfigured or does not allow.

If the link works in the menu, can you give us a link or screenshot. If you want as pm.

Best regards
Daniel
