### ISSUE TITLE
Can't customize the widget

### ISSUE THREAD

**Issue by spencejah** [mkrdip/category-posts-widget#18]
Hey so I believe to customize the plug-in, I would go to Appearances>Customize>Widgets and I'd be able to configure it. However, when I do that, it's blank and this shows up:
![blank](https://cloud.githubusercontent.com/assets/9154645/9720978/fabdfa0e-5561-11e5-9c4c-87f642a6103b.PNG)

I don't know if this is related, but a while ago, I had a separate issue where it said that I didn't have widgets enabled or something like that.

**Comment by mkrdip** [comment]
Hi, 

This could be an issue to your site only, depends on which version of WP you use. If you don't mind can you please mention the version of your WP here? 

And what do you get when you go to Appearance > Widgets page?
