### ISSUE TITLE
Widget title no longer displayed

### ISSUE THREAD

**Issue by tarax69** [mkrdip/category-posts-widget#19]
Hi, something happened a few days back, and I have no idea what. I have made no changes to the setup. The only changes made are updates to WordPress itself and any plugin updates.

I run WordPress 4.3, and version 4.1.1 of the Category Posts Widget.

The widgets now displayed without titles can be seen in the secondary sidebar (on the left side of the screen) here: http://www.whiskysaga.com/.

Any idea what has happened?
![2015-09-12_12-32-13](https://cloud.githubusercontent.com/assets/14247575/9831131/c33645ea-594a-11e5-8bc5-9eb0d01e4c3d.jpg)

**Comment by DanielFloeter** [comment]
Yes, we have a new option introduced in 4.1.1 "Show Title" and which stands as a default option to true / checked.
Kannst du mal versuchen, ob du mit dem deaktivieren und wieder aktivieren dieser Option, den Titel angezeigt bekommst oder das Plug-in ganz neu auf deiner Seite platzieren?

**Comment by mkrdip** [comment]
@DanielFloeter We had a mistake, instead of Hider Title we could've added Hide Title, which is much logical. As all the titles who've updated to latest version are gone from their widget. :-(

**Comment by tarax69** [comment]
Thanks! That solved the problem! I unchecked the 'Show Title' box, saved, then checked the box and saved again, and now the title appeared.

**Comment by bcmundim** [comment]
Hi, I noticed the same problem in the site I administer. However your suggestion didn't solve the problem completely. The titles are back but the bullets in front of the most recent posts are misaligned. Any suggestion on how to fix this? I have attached 3 snapshots of the site. One with version 4.1.0, the other with 4.1.1 and the last one with 4.1.1 with the trick of unticking the title box, save it, ticking the show title box again. Please notice the "Conference" and "Jobs" titles on the right sidebar and the five square bullets the follow each of them.

![category_posts_widget_4 1 0](https://cloud.githubusercontent.com/assets/1739481/9833358/4b15d0c2-5994-11e5-85f2-15ce6b94782d.png)
![category_posts_widget_4 1 1](https://cloud.githubusercontent.com/assets/1739481/9833359/4b19f59e-5994-11e5-8655-31a169a1cd58.png)
![category_posts_widget_4 1 1_titles_saved](https://cloud.githubusercontent.com/assets/1739481/9833360/4b1aca14-5994-11e5-9512-e7c4b534b953.png)

Thanks!

**Comment by DanielFloeter** [comment]
Hello bcmundim,

as for the bullet problem it is that in your Theme "hyperspace_new" stands styles.css CSS code we have been overwritten in an earlier version (7f21237d50f304f2fb7ca73d6c54d0c288710544).
Just delete the entry in your Theme in the file wp-content/themes/hyperspace_new/style.css the line 1931 "list-style-type: square;"
![image](https://cloud.githubusercontent.com/assets/1297656/9833511/a1975290-5999-11e5-9915-f367f3bca274.png)

**Comment by bcmundim** [comment]
Thanks! I did what you suggested and that got rid of the misaligned boxed. Ticking the "Disable widget CSS" box recovered the square bullets, but this time aligned with the links. Cheers!

**Comment by DanielFloeter** [comment]
Hello tarax69, hello bcmundim,

thank's for give us a hint about this bug "no title" after updating.
We released a bugfix with 4.1.2 (for all other updaters).
