### ISSUE TITLE
Thumbnail dimensions

### ISSUE THREAD

**Issue by kurono99** [mkrdip/category-posts-widget#20]
Thumbnail dimensions in pixels are ignored and the picture is displayed as full.

**Comment by mkrdip** [comment]
Hi, 

You need to use [Regenerate Thumbnails](https://wordpress.org/plugins/regenerate-thumbnails/) plugin.

**Comment by DanielFloeter** [comment]
... I can recommend the [Post Thumbnail Editor](https://de.wordpress.org/plugins/post-thumbnail-editor/) ;)
The UI is in my opinion only 99.9% sharped. The plug-in is still very good.
