### ISSUE TITLE
Hide widget if category is empty

### ISSUE THREAD

**Issue by mkrdip** [mkrdip/category-posts-widget#21]
As requested here: https://wordpress.org/support/topic/hide-widget-if-empty-category

We can consider it as feature request to our plugin.

**Comment by DanielFloeter** [comment]
Mrinal, what do you think?
- A new TextBox "Text if empty" and
- a new ChechBox "Hide if empty".
The side admin can choose between one of these what's a good choice for his webpage.
I'll implement it in the next days.

**Comment by mkrdip** [comment]
A check box saying "Hide if empty" would be great!

**Comment by DanielFloeter** [comment]
I added the check box.
What's with the text box. You don't like it very much?

**Comment by mkrdip** [comment]
I knocked you via [Gitter](https://gitter.im/mkrdip/category-posts-widget) to have a chat on this. :)

**Comment by BrianHenryIE** [comment]
I made a pull request with a change to show empty categories in the widget options' dropdown. My use case is to put the widget on the homepage now, and sometime in the next few weeks someone will post to that category.

**Comment by mkrdip** [comment]
As it's added to our plugin, making closing this issue for the purpose of housekeeping.
