### ISSUE TITLE
Class .cat-post-current is missing

### ISSUE THREAD

**Issue by Nyx02** [mkrdip/category-posts-widget#38]
Hello!

First of all - I love your WP plugin! 

But I just found a problem and I'm afraid it is a bug:

I use the plugin to show the last 3 posts in my sidebar (which works just fine) and when the first two posts are chosen the li element gets the class .cat-post-current, but the third (.last-child) doesn't.

I enclose 3 screenshots:

cat-post-current.png -> the code when the first link is chosen
cat-post-current-too.png -> code when the second is
cat-post-not-so-current.png -> the code when the last link is chosen

![cat-post-current](https://cloud.githubusercontent.com/assets/17642850/13526899/61f2ce62-e20b-11e5-82c4-a6248b285b70.PNG)
![cat-post-current-too](https://cloud.githubusercontent.com/assets/17642850/13526900/61f40a84-e20b-11e5-9386-7816eaa733ae.PNG)
![cat-post-not-so-current](https://cloud.githubusercontent.com/assets/17642850/13526901/61f48e82-e20b-11e5-8018-0ceb587b0908.PNG)

**Comment by DanielFloeter** [comment]
Hello Nyx02,

we know and fix this bug with this commit: https://github.com/mkrdip/category-posts-widget/commit/c480782ace4fb0dca6f8f626cf0b50ac96403fb8

The last version on wordpress.org is 4.1.5 and is released on February 4th. The commit above six days later on February 10th.

You can download the code here. We think the current code here on GitHub is stable and test a lot.
