### ISSUE TITLE
Slide Toggle Yo-Yo

### ISSUE THREAD

**Issue by genbu** [mkrdip/category-posts-widget#39]
sometimes it won't stop ...

**Comment by DanielFloeter** [comment]
Can you describe the problem or your aim in more details or leave us a url?

**Comment by genbu** [comment]
when I click the Title it keeps up and down looping, but sometime not often, it recover it self when I click save button. But if it looping, I must refresh the page to recover it.
![category-post looping](https://cloud.githubusercontent.com/assets/7300107/14039544/208004c8-f290-11e5-9f3a-e000441a3393.jpg)

**Comment by DanielFloeter** [comment]
You really use the actual code? When yes, were it is looping on costomizer or/and Settings > Widgets? Which browser do you use ... ? Thank.

**Comment by genbu** [comment]
yes, on setting > widgets, chrome

**Comment by DanielFloeter** [comment]
Hello Genbu,

you're right. I can reproduce the bouncing-ball toggle - and fixed it.

Enjoy.

**Comment by genbu** [comment]
how do you do that exactly?

**Comment by DanielFloeter** [comment]
With Google ;) "bad bouncing ball with slidetoggle jquery" I found this [http://stackoverflow.com/questions/3329874/eliminate-bouncing-ball-effect-on-slidetoggle](http://stackoverflow.com/questions/3329874/eliminate-bouncing-ball-effect-on-slidetoggle)

jQuery has a lot of functions for the event queuing. .stop () is the simplest and most effective.

[https://github.com/mkrdip/category-posts-widget/commit/d3e699679b82bc518ea66467ac796a46746d227f](https://github.com/mkrdip/category-posts-widget/commit/d3e699679b82bc518ea66467ac796a46746d227f)
