### ISSUE TITLE
Make Widget CSS optional, defaulting off

### ISSUE THREAD

**Issue by deltafactory** [mkrdip/category-posts-widget#4]
Some discussion here: https://wordpress.org/support/topic/disabling-styles?replies=5

In general, changing the default behavior of a mature plugin is a bad idea. It reduces trust of the plugin update system when it impacts the current installation in unpredictable ways.

It would be totally acceptable to enable this option on a new installation.

**Comment by mkrdip** [comment]
@DanielFloeter Bro, would you mind to check this issue? Seems interesting. :)

**Comment by DanielFloeter** [comment]
I wanted to stay backwards compatible, ie delete any existing CSS classes. 
The option for each Widget instance.
