### ISSUE TITLE
need Title background color

### ISSUE THREAD

**Issue by genbu** [mkrdip/category-posts-widget#40]
how to add background color to category title? or maybe background url option

**Comment by DanielFloeter** [comment]
For the title you can use two CSS classes: 'post-title' or  'cat-post-title'

.post-title {
    background-color: lightblue;
}
.post-title:hover {
    color: green;
}

I'm not realy know what you mean with '... background ulr option ...'. We had a filter for the title you can change/filter the rendered HTML for the title. Any way the title is a link to the shown post.

**Comment by genbu** [comment]
It's okay I've done it.

the Idea is dynamically change title background like this:
![dinamically-change-background-color](https://cloud.githubusercontent.com/assets/7300107/14039918/5ce85fce-f294-11e5-80c1-7a308ef8a90c.jpg)

So, I add an option for ackground color on the widget like this:
![add-option-background-color](https://cloud.githubusercontent.com/assets/7300107/14039926/74a4b766-f294-11e5-9144-bbc65f1aef5e.jpg)

The code is like this:

On widget title I add some code like this :
			// Widget title
			if( !isset ( $instance["hide_title"] ) ) {
    			// echo $title;
				if( isset ( $instance["bgcolor"] ) ) {
	    			echo $before_title = str_replace('indigo"', ''. $instance["bgcolor"]. ' "', $before_title);
	    		}else{
	    			echo $before_title;
	    		}
				if( isset ( $instance["title_link"] ) ) {
					echo '<a href="' . get_category_link($instance["cat"]) . '">' . $instance["title"] . '</a>';
				} else {
					echo $instance["title"];
				}
				echo $after_title;
			}


Add instance on function form($instance)
		$title                = $instance['title'];
		$bgcolor              = $instance['bgolor'];

And label like this

				<p>
					<label for="<?php echo $this->get_field_id("bgcolor"); ?>">
						<?php _e( 'Background Color','categoryposts' ); ?>:
						<input class="widefat" style="width:50%;" id="<?php echo $this->get_field_id("bgcolor"); ?>" name="<?php echo $this->get_field_name("bgcolor"); ?>" type="text" value="<?php echo esc_attr($instance["bgcolor"]); ?>" />
					</label>
				</p>
