### ISSUE TITLE
"read me" changes for wordpress.org

### ISSUE THREAD

**Issue by markkap** [mkrdip/category-posts-widget#66]
1. Need a link to the latest announcement to be visible before anything else. maybe link to http://tiptoppress.com/category/category-posts-widget/ ?

2. the "category recent posts" tag is useless, no one probably searches for it, better to replace it with "recent posts"

3. link to the full documentation of the plugin at http://tiptoppress.com/category-posts-widget/documentation/

**Comment by DanielFloeter** [comment]
About 2. The tag name is 'recent posts'? There is no 'category recent posts' tag.
