### ISSUE TITLE
Archive menu

### ISSUE THREAD

**Issue by nickpastor** [mkrdip/category-posts-widget#7]
Hello ,
I hope this is the right place.
An unmentioned feature of this plug-in is that the archive menu shows posts from the same category as the one selected in the set up.

I used this on a single site installation, and found this really useful considering that there could be many post over time.
Unfortunately on multisite it only works on the main site on the second site I get page not found and a search box. 
Stranger still if I click on the search button without entering anything in the text field I get posts from all the categories...

Would it be possible to have the archive menu working like this as a feature of the plug-in, and of course, that it worked on multisite installations.
Thank you.

**Comment by mkrdip** [comment]
Hey @nickpastor, 

Thank you for bringing up the issue here. 

Would you mind to provide us some screenshot of the issue here? I'll be glad to check. 

Sorry for the delay.

**Comment by markkap** [comment]
closing as there was no response
