### ISSUE TITLE
Fatal Error after WP 4.5.2 and 4.1.9 upgrade

### ISSUE THREAD

**Issue by futurex5** [mkrdip/category-posts-widget#75]
Upgraded WP to 4.5.2 then upgraded category-posts-widget to 4.1.9 and got this:

Plugin could not be activated because it triggered a fatal error.
Parse error: syntax error, unexpected T_FUNCTION in /home/content/18/3900718/html/wp-content/plugins/category-posts/cat-posts.php on line 58

**Comment by markkap** [comment]
Hi, some time ago we have decided not to support php versions 5.2.x which are very old and insecure. It sounds like you are running such a version so please, check that this assumption is true, and if so contact your host to help you upgrade to a more recent php version (the plugin will work with 5.3 and above but you probably should upgrade to 5.6 if you can)

**Comment by futurex5** [comment]
I upgraded to PHP 5.4 and that fixed it!  It was on 5.2.  Thanks.
